### ISSUE TITLE
Twig files not recognised

### ISSUE THREAD

**Issue by gablittledevshop** [forumone/gesso-theme-wordpress#105]
Hello, I installed this theme in Wordpress version 5.2.1 but doesn't seem to be working (the Timber plugin is also installed).  It looks like it's unable to recognise the templates folder.  When I view the homepage all I see is a blank page, the html is not rendering properly.

Is there something I am missing?

Thanks!

**Comment by coreylafferty** [comment]
@gablittledevshop Have you run the setup commands in the README?  You'll need Composer, NPM and Grunt installed and then run:

```
npm install
grunt
```

That should install things and compile Pattern Lab and the CSS files.  Then WordPress should be able to read the templates.

**Comment by gablittledevshop** [comment]
@coreylafferty yes, I have all the tools installed and ran all the commands which is why I wasn't sure if there was something else going on.

**Comment by coreylafferty** [comment]
@gablittledevshop huh, that is strange.  
Are there any specific error messages you're seeing, either from WordPress or while running 'npm install' or 'grunt'?  
Do you see a themes/gesso/pattern-lab/source/_patterns/ directory? (you should after running npm install)  
Do you see a themes/gesso/_starter-kit/ directory? (you shouldn't after running npm install) 
Are Timber and Gesso enabled?  And you're using the code from the 2.x branch?
You might need to turn on PHP error reporting in WordPress to get more info if everything else above seems fine and nothing is reporting any errors.

**Comment by gablittledevshop** [comment]
@coreylafferty to answer your questions:

> Are there any specific error messages you're seeing, either from WordPress or while running 'npm install' or 'grunt'?

I don't get any errors.

> Do you see a themes/gesso/pattern-lab/source/_patterns/ directory? (you should after running npm install)

Yes, I see it there.

> Do you see a themes/gesso/_starter-kit/ directory? (you shouldn't after running npm install)

I do not see it there.

> Are Timber and Gesso enabled? And you're using the code from the 2.x branch?

Yes, both are enabled.  Code is from the 2.x branch.

> You might need to turn on PHP error reporting in WordPress to get more info if everything else above seems fine and nothing is reporting any errors.

I will try this and let you know what I find.

Thanks!

**Comment by coreylafferty** [comment]
Ok, thanks! I’ll spin up a new copy of WordPress and Timber and make sure no recent changes have affected anything. Based on what you’re describing, it should be working... but let me know if you find anything and I’ll do the same. 

If you like, you might also try the 3.x branch and see if that works for you. It’s still in development, but it uses the Node version of Pattern Lab and requires less overhead to run.

**Comment by giorgioriccardi** [comment]
I have the same issue, I did try both 2.x and 3.x, there is no rendering of the Twigs templates. It just renders an empty html markup structure:
```<html><head></head><body></body></html>```
There are no errors at any level, so I wonder if I'm missing something that I'm supposed to do in order to trigger Timber to render the Twig files

**Comment by gablittledevshop** [comment]
@coreylafferty after turning the PHP error reporting on, I don't see any errors.

**Comment by coreylafferty** [comment]
@gablittledevshop @giorgioriccardi I believe the issue is a bug in the newest version of Timber.

See the two issues from the Timber repo below.  To get things working until a new version is released you can use the test version Jared links to in both of the issues or downgrade to version 1.9.4.

https://github.com/timber/timber/issues/2016
https://github.com/timber/timber/issues/2020

**Comment by gablittledevshop** [comment]
@coreylafferty thanks, I will have a look!

**Comment by gablittledevshop** [comment]
@coreylafferty just letting you know the fix provided by Jared in the links is working for me.

Thanks!

**Comment by giorgioriccardi** [comment]
@coreylafferty with Timber 1.9.4 it works again.
Thank you!
