### ISSUE TITLE
Site attributes

### ISSUE THREAD

**Issue by cssgirl** [forumone/gesso-theme-wordpress#113]
In the html-header.twig file the conditional doctypes for IE are still using the PHP code for doctypes. They need to be replaced with the correct variables.

**Comment by coreylafferty** [comment]
> 
> 
> In the html-header.twig file the conditional doctypes for IE are still using the PHP code for doctypes. They need to be replaced with the correct variables.

At this point I think we can just get rid of the IE conditionals.  We no longer use them in the other version of Gesso.  You can remove them, or I'll do it as part of adding in the 3.1 updates.

**Comment by cssgirl** [comment]
@coreylafferty added a PR here: https://github.com/forumone/gesso-wp/pull/114
