### ISSUE TITLE
Pattern Lab -> WordPress template not retaining spacing 

### ISSUE THREAD

**Issue by cssgirl** [forumone/gesso-theme-wordpress#174]
I'm running into a weird bug with the most recent version of Gesso for WordPress. It seems when you add classes as a variable the spacing isn't being retained when it is added in WordPress:

I have a component - `site-name` in this case - where I added a `modifier_classes` variable. 

Pattern Lab Code:
```
<a class="site-name{% if modifier_classes %} {{ modifier_classes }}{% endif %}" href="{{ url }}" title="{{ 'Home' }}" rel="home">
  <h1 class="site-name__text">{{ site_name }}</h1>
</a>
```

Integration code:
```
{% include '@components/site-name/site-name.twig' with {
  'modifier_classes': 'site-name--footer'
} %}
```

Output in WordPress source:
```
<a class="site-namesite-name--footer" href="" title="Home" rel="home">
  <h1 class="site-name__text"></h1>
</a>
```

Even though the space is present in my Pattern Lab twig file between the static class and the `modifier_classes` variable, when I add it to my WordPress template, it removes the spaces. This happens when I remove the conditional and just have a space between "site-name" and `{{ modifier_classes }}` This also happened to me using the menu component and custom classes being pulled in from WordPress.

Screenshot of menu issue:
![image](https://user-images.githubusercontent.com/3473355/77774762-f7180680-7021-11ea-9bed-0b2a397a66fb.png)

You can also see the `site-name` class issue a few lines above with no spacing as well. The spacing works exactly as expected within Pattern Lab.

I resolved the menu issue by moving my call for `{{ item.class }}` to the front of the class list in code like so:
`<a class="{% if item.class %} {{ item.class }} {% endif %} menu__link {% if item.children %} has-subnav{% endif %} {% if item.current %} is-active{% endif %}" href="{{ item.link }}">{{ item.title }}</a>`

Where prior I had it as:
` <a class="menu__link {% if item.children %} has-subnav{% endif %} {% if item.current %} is-active{% endif %} {% if item.class %} {{ item.class }} {% endif %}" href="{{ item.link }}">{{ item.title }}</a>`

Again, menus worked perfectly fine in WordPress and spacing was respected. When integration into the WordPress began the spaces were dropped on that end.

**Comment by timnolte** [comment]
@cssgirl  this is not a bug. You didn't include a space before your if condition. Your code should be this:
```
<a class="site-name {% if modifier_classes %} {{ modifier_classes }}{% endif %}" href="{{ url }}" title="{{ 'Home' }}" rel="home">
  <h1 class="site-name__text">{{ site_name }}</h1>
</a>
```
Notice the space before the `{%`. The space you have here `%} {{` is not seen as part of the output but as part of the code/logic.

**Comment by cssgirl** [comment]
A lot of variables out of the box in Gesso don't have that pattern of spacing,[ see this example from our default menu.twig file](https://github.com/forumone/gesso-wp/blob/3.x/source/_patterns/04-components/menu/menu.twig):

```
<li class="menu__item{% if child.children %} has-subnav{% endif %}">
  <a class="menu__link{% if child.children %} has-subnav{% endif %}{% if child.current %} is-active{% endif %}" href="{{ child.link }}">{{ child.title }}</a>
  {% if child.children %}
    <ul class="menu menu__subnav">
      {% for grandchild in child.children %}
        <li class="menu__item">
          <a class="menu__link{% if grandchild.current %} is-active{% endif %}" href="{{ grandchild.link }}">{{ grandchild.title }}</a>
        </li>
      {% endfor %}
    </ul>
  {% endif %}
</li>
```

I've always included the space within the conditional, before the variable, not before the entire conditional.

**Comment by dcmouyard** [comment]
@cssgirl Sounds like Twig is running `spaceless` or some other [whitespace control ](https://symfony.com/blog/better-white-space-control-in-twig-templates)somewhere, which removes the empty spaces between items. Perhaps it’s set globally somewhere?

The pattern we’ve been using recently in Gesso for passing in classes would bypass this:
```
{% set classes = [
  'component-class',
  modifier_classes ? modifier_classes,
]|join(' ')|trim %}

<div class="{{ classes }}">
```

**Comment by cssgirl** [comment]
@dcmouyard - this fixed the issue I was running into. Thanks so much.
