### ISSUE TITLE
Minify CSS Files

### ISSUE THREAD

**Issue by sbrack8t** [forumone/gesso-theme-wordpress#194]
Add a gulp process to minify css for productions

**Comment by timnolte** [comment]
@sbrack8t on the McCabe-RWJF project I used `cssnano` to do this.
https://github.com/forumone/McCabe-RWJF-WordPress/blob/stable/services/wordpress/web/wp-content/themes/rwjf-alignment/package.json#L30
https://github.com/forumone/McCabe-RWJF-WordPress/blob/stable/services/wordpress/web/wp-content/themes/rwjf-alignment/gulpfile.js#L87

**Comment by coreylafferty** [comment]
Closed by #268
