### ISSUE TITLE
jQuery Version Used in Pattern Lab is Insecure.

### ISSUE THREAD

**Issue by timnolte** [forumone/gesso-theme-wordpress#204]
https://github.com/forumone/gesso-wp/blob/5a7da9b8f5be21e81c46c0af8d4b0063c249f656/source/_meta/_01-foot.twig#L1

**Comment by coreylafferty** [comment]
I've updated the version in Pattern Lab to match that in WordPress.  Will probably revisit removing jQuery altogether in the near future.
