### ISSUE TITLE
Lint PHP and fix as necessary

### ISSUE THREAD

**Issue by kmonahan** [forumone/gesso-theme-wordpress#205]
Similar to #374 on the Drupal side, we should run PHP Code Sniffer Gesso and fix anything that's out of line with Wordpress's code standards, using the sniffs available at https://github.com/WordPress/WordPress-Coding-Standards. Goal is to ensure that a new install of Gesso WP will run cleanly.

Note: As with the Drupal PR, we're just concerned with PHP here as there's already ESLint for JS and Stylelint for CSS in place. If we want to change any JS or (S)CSS linting rules, we should alter those files so that we don't end up with conflicts between PHP Code Sniffer and other linting tools.

**Comment by timnolte** [comment]
Just a note that https://github.com/forumone/gesso-wp/blob/3.x/phpcs.xml.dist has already been added to assist with this. Looks like it will need to be updated to not include CSS/SASS since you are using Stylelint already.

**Comment by timnolte** [comment]
I didn't include a composer.json file which will be needed with `wp-coding-standards/wpcs` and `dealerdirect/phpcodesniffer-composer-installer` as required dev dependencies.
