### ISSUE TITLE
Evaluate accessibiilty functionality / includes for FacetWP

### ISSUE THREAD

**Issue by traverus** [forumone/gesso-theme-wordpress#251]
Currently when FacetWP is 'turned on' in gesso there are a myriad of accessibility issues. Look at either having a default JavaScript include or modify the FacetWP DOM via hooks to better account for this issue.

**Comment by tropicandid** [comment]
Outdated issue: https://facetwp.com/help-center/add-on-features-and-extras/accessibility-support
