### ISSUE TITLE
Gesso Should Be Setup as a Parent Theme on All Builds to Allow Upgrades During Support

### ISSUE THREAD

**Issue by timnolte** [forumone/gesso-theme-wordpress#310]
As we continue to attempt to support all various versions of Gesso within Support it's becoming increasingly difficult to continue supporting the model that Gesso is a starter theme that never gets upgraded. As we are attempting to test out sites for PHP 8 compatibility Gesso 4, due to the Pattern Lab version, is not compatible with PHP 8. This results in failures to be able to even build Gesso. It is not sustainable long term for Gesso to be used as a starter theme that is customized beyond the ability to keep it updated. Gesso should be setup as a Parent Theme that can be upgraded on any site using it and the child themes updated to accommodate the changes.

**Comment by kmonahan** [comment]
Maybe I'm misunderstanding how child themes works, but it seems to me that you'd just be setting up Pattern Lab and the build process twice and still hit the same issues when you needed to upgrade the child theme. Perhaps we can discuss further at the next theme development checkin.

**Comment by timnolte** [comment]
Well, with Gesso <=4 what's done is done. What I'd like to focus on is the next version of the theme, and since that isn't Pattern Lab, that is where I want to dig into this and change the path we're on, so as not to end up the in the same situation we now find ourselves in with Gesso <=4. I want us to think about this work from an ongoing support standpoint and not just the new build process. There are other theme efforts doing this with block-based themes:
* https://themeshaper.com/2021/05/27/blockbase-a-parent-theme-for-block-themes/
* https://wptavern.com/designing-block-based-wordpress-child-themes-with-a-single-json-file
* https://www.godaddy.com/garage/how-to-create-a-block-child-theme-in-wordpress/
* https://fullsiteediting.com/the-state-of-child-themes/
