### ISSUE TITLE
Update Gesso 4.x with the Latest Pattern Lab 5.16.1 for PHP 8 Support

### ISSUE THREAD

**Issue by timnolte** [forumone/gesso-theme-wordpress#312]
In the even that new builds start before the new WP theme is out and people are ready to start building with it, we need to get Gesso updated to using the latest Pattern Lab version in order to ensure that Gesso is compatible with PHP 8. PHP 7.4 is set to be EOL after November 28 of this year.

**Comment by coreylafferty** [comment]
This is in the latest release.
