### ISSUE TITLE
Auto-applied l-constrain classes causing inconsistency

### ISSUE THREAD

**Issue by jackmakesthings** [forumone/gesso-theme-wordpress#336]
I think I get the intent of adding l-constrain/l-constrain--small to blocks with JS, but it is creating some mismatches in padding when elements are nested.
![Screenshot 2022-05-16 at 14-24-59 Very Scary Celery – Just another WordPress site](https://user-images.githubusercontent.com/3606708/168658316-40a3e578-d23f-490b-9163-03186ad55e0a.png)

The left column here is getting double padding because both "Contact Us" and the text under it get those classes added. On the right, the paragraph gets the class & padding but the list block doesn't, causing a misalignment. And these classes can't be removed in the editor, which is frustrating.

On Gates MRI ([site](https://dev.mri.gates.byf1.io/) / [repo](https://github.com/forumone/gateshosting-mri/tree/main/public/wp-content/themes/gesso)) we ended up not using l-constrain classes at all and letting Wordpress do most the work by making use of the alignwide/alignfull classes, the layout settings in theme.json, plus some careful use of descendant selectors (ie, setting a max width on direct children of groups, rather than on individual blocks.) Maybe this is an approach to look into?

**Comment by kmonahan** [comment]
@jackmakesthings The classes can be removed in the editor. There's an alternate block style you can use to remove them.

**Comment by jackmakesthings** [comment]
Totally overlooked that, thanks!

**Comment by kmonahan** [comment]
In case anyone else digs this issue up, it's the "No Max Width" block style.
<img width="266" alt="Screen Shot 2022-05-16 at 1 39 50 PM" src="https://user-images.githubusercontent.com/6145435/168660852-573ebd59-1b72-4a8f-8b7e-4a6b6347826a.png">
