### ISSUE TITLE
Issue(s) with l-constrains

### ISSUE THREAD

**Issue by cssgirl** [forumone/gesso-theme-wordpress#337]
I ran into an issue - which may or may not be intentional - if you try to add a class via the advanced tab for a block (in my scenario it was the group block), it will not allow you to add `l-constrain` as the class. It immediately strips it out:

https://user-images.githubusercontent.com/3473355/169406150-f27661a6-4c75-4edf-a48e-39a99654dfaf.mp4

**Comment by timnolte** [comment]
It should be known that the CSS Class field in Advanced is where all custom classes go, even the custom styles. If you are attempting to add one-off classes manually here you are going to run into problems.

**Comment by jackmakesthings** [comment]
Seeing the same issue. Also happened when trying to add a class to a Columns block. Any other class works fine, it's just "l-constrain" that gets removed.


@timnolte Not sure what you mean - isn't adding classes manually the whole point of this field? It's fine if things are getting added there programmatically, but we should still be able to edit it.

**Comment by timnolte** [comment]
@jackmakesthings so I have sort of 2 points in that regard.

1. Depending on how we are programmatically adding classes this may cause problems, and my general rule would be to stick with using WordPress Core Blocks API for doing this like with adding custom Styles that can be easily chosen by a content editor.
2. If we are creating an editing experience where by we are instructing content editors to know CSS class names and manually entering them in that class field that is a very poor and error prone experience that I would steer clear of.

**Comment by jackmakesthings** [comment]
Sure - in situations where I've wanted to put a class on something the user would be adding or editing, I'd just as soon use the styles api or pre-set it in a block pattern. Lindsey and I are specifically working on template parts here which are not really meant to have their advanced settings changed by the editor - just to be set up once in the theme and then filled with content. I wouldn't ask users to know how to set up l-constrain containers, but I'd like to be able to do that myself as the theme dev, without necessarily exposing those classes as custom style options.
