### ISSUE TITLE
Remove the requirement of having the block library as a dependency

### ISSUE THREAD

**Issue by tropicandid** [forumone/gesso-theme-wordpress#345]
Would it be possible to decouple the f1 block library from Gesso 5? I don't fully understand the nuances just yet, but have we thought about making the block library an optional addition somehow?

**Comment by kmonahan** [comment]
Yes, we've thought about it. It really comes down to whether there will be more projects that use it versus more projects that do not. What's your use case for wanting to remove it?

**Comment by timnolte** [comment]
These really should be done via the plugin code and not be in Gesso:
* https://github.com/forumone/gesso-wp/blob/a9fd2cc7afc3240f6ff5e9bf20ba91e9e7d7aaff/functions.php#L51-L90
* https://github.com/forumone/gesso-wp/blob/a9fd2cc7afc3240f6ff5e9bf20ba91e9e7d7aaff/source/editor-scripts.js#L30-L44

**Comment by timnolte** [comment]
Gesso should be updated in a way that actually checks for the availability of the plugin and only then will it load. And as much of the plugin loading as possible should be contained within the plugin and not in Gesso like any other block library plugin.

**Comment by tropicandid** [comment]
So, my particular use case in this scenario was a client that had a large number of restrictions on additional plugins. We are only contracted to deliver a theme, so every additional dependency poses a risk. This may be an isolated case but given the removal of timber as a dependency, Gesso 5 could have been a good fit if we could strip that one too and if the timeline wasn't so crazy on this one.

**Comment by coreylafferty** [comment]
Fixed by #346
