### ISSUE TITLE
generate theme.json as unminified / formatted

### ISSUE THREAD

**Issue by jackmakesthings** [forumone/gesso-theme-wordpress#383]
Small improvement - it would be easier to inspect the theme.json if it were formatted with linebreaks & indents rather than compressed to one line.

**Comment by tropicandid** [comment]
Adding a dev breadcrumb here. The modification to un-minify this will likely need to start by making changes to how we are leveraging renderjson: https://github.com/forumone/gesso-wp/blob/5.x/lib/configLoader.js

**Comment by timnolte** [comment]
We should be able to add spacing to the `JSON.stringify` here: https://github.com/forumone/gesso-wp/blob/5.x/lib/renderJson.js#L103C9-L103C23

```javascript
return JSON.stringify(themeSettings,null,2);
```

**Comment by cssgirl** [comment]
I think we can close this issue since we will no longer be generating `theme.json` by passing design tokens and settings from theme-settings.json? ref: https://github.com/forumone/gesso-wp/pull/444
