### ISSUE TITLE
Misc. updates to the config rendering process

### ISSUE THREAD

**Issue by jackmakesthings** [forumone/gesso-theme-wordpress#399]
A few changes I have been making on projects lately that could be backported to gesso:

- WP has built-in fluid sizing and we have a map for responsive font-sizes - these can work together with adjustments to the addToFontSizes function in renderJson.js
- change the constraint mapping in the same file so sm => content & md => wide content (currently it's md and lg respectively); better reflects how our designs & the WP container system relate to each other

**Comment by cssgirl** [comment]
I think we can close this one based on the changes made in https://github.com/forumone/gesso-wp/pull/444
