### ISSUE TITLE
Update Editor Style registry to relative path

### ISSUE THREAD

**Issue by tropicandid** [forumone/gesso-theme-wordpress#406]
Per the documentation warnings here: https://developer.wordpress.org/reference/functions/add_editor_style/ we need to update how we are pulling in editor styles so that we don't have to worry about basic auth on f1 hosting or pantheon.

"If you’re working locally, be aware that using an absolute URL (eg. via [get_template_directory_uri](https://developer.wordpress.org/reference/functions/get_template_directory_uri/)) won’t work if you’re using HTTPS with a self-signed certificate. This is due to [wp_remote_get](https://developer.wordpress.org/reference/functions/wp_remote_get/) being used to retrieve your stylesheet, which fails (silently) if a requested URL’s certificate isn’t included in WordPress’ internal store of allowed certificates."

Update the path for the editor-styles.css at: https://github.com/forumone/gesso-wp/blob/041960eb6000be0a9bb48d238c5c61b7fe8c2701/functions.php#L202

to

`add_editor_style( './build/css/editor-styles.css' );`

**Comment by jackmakesthings** [comment]
Something to be aware of - copying this change over to the editor-scripts.js file causes it to quietly fail to load. That said, it doesn't seem to run into the loading issue that the stylesheets did in the first place, so there should be no need.

**Comment by tropicandid** [comment]
PR created to address this: https://github.com/forumone/gesso-wp/pull/418
