### ISSUE TITLE
Add theme support for responsive embeds

### ISSUE THREAD

**Issue by cssgirl** [forumone/gesso-theme-wordpress#409]
Right now, out of the box we do not have responsive embeds on by default. They probably should be?

We should add the following to functions.php:

```
// Add support for responsive embeds.
add_theme_support( 'responsive-embeds' );
```

**Comment by cssgirl** [comment]
PR: https://github.com/forumone/gesso-wp/pull/412

**Comment by jackmakesthings** [comment]
Thanks! Merged.
