### ISSUE TITLE
Update to use Node 18

### ISSUE THREAD

**Issue by rjensen26** [forumone/gesso-theme-wordpress#415]
Need to update gesso to be compatible for Node  18 since Node 16 is out of Security Updates..

<img width="734" alt="Screenshot 2023-10-16 at 12 24 08 PM" src="https://github.com/forumone/gesso-wp/assets/5650670/cb95935b-1abc-475e-9ad5-55021e23a945">

**Comment by tropicandid** [comment]
This update has been completed and deployed
