### ISSUE TITLE
Invalid Use of `wp_enqueue_block_style` in the `functions.php`

### ISSUE THREAD

**Issue by timnolte** [forumone/gesso-theme-wordpress#423]
https://github.com/forumone/gesso-wp/blob/231c137c2ae4bc12f66d2ada09d572440c996994/functions.php#L83

There is no `path` argument for the `wp_enqueue_block_style` method.

https://developer.wordpress.org/reference/functions/wp_enqueue_block_style/

**Comment by tropicandid** [comment]
This has been approved and merged
