### ISSUE TITLE
Design tokens, config & theme.json - for discussion

### ISSUE THREAD

**Issue by jackmakesthings** [forumone/gesso-theme-wordpress#439]
As WP keeps evolving, more and more of the tokens we've historically kept in a yaml config are now expected to be part of theme.json. We have scripts to convert some of these variables over, but it's increasingly feeling like we've created extra work here when we could just hand-edit theme.json. There are also still gesso utilities for things like side padding and container widths, which at this point are pretty well-landed in WP theme core. Meanwhile, core themes have lots of pre-baked patterns we could take advantage of, but currently tend to build from scratch.

I would be very interested to try starting a future WP project with one of the core themes as a base - twentytwentyfour presumably - instead of gesso. Based on the last few projects I've been on, I don't think it would cost us much time, and might even save time, especially if we lean into the core patterns & templates.

WP seems very committed to going forward with theme.json and block.json as core sources of truth, and I think it'd serve us well as a team to learn how to work with both. At this point, I'd argue that the Drupal and WP gesso authoring experiences are so different that there's less need to make them use the same tokens and utilities, compared to when they both ran on twig.

But I recognize this may not be everyone's opinion, and it could raise issues for support & for other devs inheriting the project, so let's discuss! Maybe there's some way to do an internal test project first.

**Comment by cssgirl** [comment]
Action items:
- Remove design tokens, design tokens scripts + files
- Utilize theme.json to replace the tokens with CSS variables
- Go through theme source and remove design token refs, replace with new CSS variables

**Comment by cssgirl** [comment]
In progress work: https://github.com/forumone/gesso-wp/pull/444

**Comment by cssgirl** [comment]
Closing this issue as the work has been completed as a part of this issue: https://github.com/forumone/gesso-wp/issues/441 and PR: https://github.com/forumone/gesso-wp/pull/444

**Comment by cssgirl** [comment]
Completed via https://github.com/forumone/gesso-wp/pull/444
