### ISSUE TITLE
Theme cleanup for vestigial code

### ISSUE THREAD

**Issue by tropicandid** [forumone/gesso-theme-wordpress#441]
Please audit and clean up the current gesso theme for things that may now be vestigial from when we were using twig or perhaps referencing drupal specific items. 

Places to start:
* lib folder
* f1-block-library style/js enqueues ( be sure to add example of how to re-implement in readme)

**Comment by timnolte** [comment]
@tropicandid & @christopherhodges FYI, that there was already some cleanup that happened in Rifaci that can be referenced as well.

https://github.com/forumone/gates-rifaci-wp

**Comment by timnolte** [comment]
I'll keep an eye out here for changes/clean-up that happens that I'll want to make to Rifaci as well.

**Comment by timnolte** [comment]
FYI, I had created and issue for Rifaci when Corey opened up a PR for some clean-up items in Gesso WP. https://github.com/forumone/gates-rifaci-wp/issues/138

**Comment by cssgirl** [comment]
In progress work: https://github.com/forumone/gesso-wp/pull/444

**Comment by cssgirl** [comment]
Closing this issue as the work has been completed as a part of this issue: https://github.com/forumone/gesso-wp/issues/441 and PR: https://github.com/forumone/gesso-wp/pull/444
