### ISSUE TITLE
Proposal: Review and housekeep default gesso colors

### ISSUE THREAD

**Issue by tropicandid** [forumone/gesso-theme-wordpress#448]
* Similarly to how we've been cleaning up the theme for old design tokens and classes, lets take a look at the copious amount of colors that exist upon initial start up and see what we can remove as default.

**Comment by cssgirl** [comment]
As part of the cleanup happening in https://github.com/forumone/gesso-wp/pull/444 I've renamed the specific brand names (blue, ocean-blue) to primary and secondary so they are more generic I left the color values in as examples of good naming practices (eg: dark, dark-1, light, base, etc).
