### ISSUE TITLE
Generic archive twig template with loop and pagination 

### ISSUE THREAD

**Issue by elvismdev** [forumone/gesso-theme-wordpress#9]
Create a generic twig template files for archive pages, loop and pagination components.

Example files for reference where this work is already made in another project:
[`archive.twig`](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/archive-in_the_news.twig)
[`loop.twig`](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/news-card.twig)
[`pagination.twig`](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/pagination.twig)
[`content-none.twig`](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/content-none.twig)

**Comment by dmoon79** [comment]
@elvismdev Are you referring to making something that is much different than the following files that are already present?

views/archive.twig
templates/loop.twig
templates/pager.twig
views/404.twig

**Comment by elvismdev** [comment]
I'm recommending to make a generic `archive.twig` file similar to [this one here](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/archive-in_the_news.twig)  with the difference that instead of `news-card.twig` to be included, that one will be generically named `content.twig`

And `content.twig` will be holding only everything that goes inside `<article>...</article>` tags, like the code of [this file here](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/news-card.twig)

For the case that while looping at `archive.twig` there are no posts to display, then it will fall back to `content-none.twig` [like this one](https://github.com/forumone/PFAW-main-site/blob/5b76377f674e290c4b1e21de2b26474002c119ee/public/wp-content/themes/pfaw/views/content-none.twig)

After that, I think you can get rid of `templates/loop.twig` file if there's no other place used or called/included.

For pagination, see the linked files below for reference on how I did it there. So you can also "generify" that idea as well.

[`pagination.twig`](https://github.com/forumone/PFAW-main-site/blob/stable/public/wp-content/themes/pfaw/views/pagination.twig)
And [see here at line 70](https://github.com/forumone/PFAW-main-site/blob/stable/public/wp-content/themes/pfaw/views/page-action-center.twig#L70) how I'm calling `pagination.twig` and passing it over only the pagination object for the file to use, you can implement the same at the bottom of your `archive.twig` file after the FOR loop.

**Comment by elvismdev** [comment]
This is good enough how is setup now, closing this issue.
