### ISSUE TITLE
site_name.twig component does not use proper value to link homepage

### ISSUE THREAD

**Issue by wroxbox** [forumone/gesso-theme-wordpress#95]
the component site_name.twig is linking to not the frontpage defined in wp settings.

```
<a class="site-name" href="{{ url|raw }}" title="{{ 'Home' }}" rel="home">
  <h1 class="site-name__text">{{ site_name|raw }}</h1>
</a>
```
Fix is to use site_url value defined in parameter

```
<a class="site-name" href="{{ site_url|raw }}" title="{{ 'Home' }}" rel="home">
  <h1 class="site-name__text">{{ site_name|raw }}</h1>
</a>
```

**Comment by coreylafferty** [comment]
@wroxbox This is working as intended -- the site-name.twig and site-logo.twig Pattern Lab files print out {{ url|raw }}.  For Pattern Lab, the value for 'url' is defined in the data.yml file.  For WordPress, it passes site.url in as the value of 'url' from the base.twig template.

example:
```
{% include '@components/site-name/site-name.twig' with {
    url: site.url,
    site_name: site.title
} %}
```

**Comment by wroxbox** [comment]
You are right. I have some other weird problem then with the frontpage link. Sorry spamming this issue. Thought the site_url was the answer in the first place.
 I don't know what I am missing then but when my site is running in port: 8181, the frontpage link takes to frontpage and some redirect happens after it to url without port and gives connection error.

ttt.localhost:8181/wordpress (frontpage) takes to ttt.localhost/wordpress.
